version: '2'
services:
  authserver-app:
    image: authserver
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://authserver-mariadb:3306/authserver
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  authserver-mariadb:
    extends:
      file: mariadb.yml
      service: authserver-mariadb
